var TestResponse = {
  "login": "chrisco",
  "id": 37781,
  "avatar_url": "https://avatars.githubusercontent.com/u/37781?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/chrisco",
  "html_url": "https://github.com/chrisco",
  "followers_url": "https://api.github.com/users/chrisco/followers",
  "following_url": "https://api.github.com/users/chrisco/following{/other_user}",
  "gists_url": "https://api.github.com/users/chrisco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/chrisco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/chrisco/subscriptions",
  "organizations_url": "https://api.github.com/users/chrisco/orgs",
  "repos_url": "https://api.github.com/users/chrisco/repos",
  "events_url": "https://api.github.com/users/chrisco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/chrisco/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Christopher Comella",
  "company": "linkedin.com/in/comella",
  "blog": "http://twitter.com/chrisco",
  "location": "Boulder | Denver | Fort Collins | Washington DC | Sweden",
  "email": null,
  "hireable": true,
  "bio": null,
  "public_repos": 28,
  "public_gists": 1,
  "followers": 6,
  "following": 35,
  "created_at": "2008-12-02T13:22:44Z",
  "updated_at": "2015-10-24T20:31:04Z"
}